---
services:
  rlsbin:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    command:
      - rlsbin
      - --rls-ip
      - 0.0.0.0
      - --rls-port
      - "8081"
      - --grpc-reflection-service
      - -vvv
    ports:
      - 8081:8081
  envoy:
    image: envoyproxy/envoy:v1.31-latest
    depends_on:
    - rlsbin
    - upstream
    command:
    - /usr/local/bin/envoy
    - --config-path
    - /etc/envoy.yaml
    - --log-level
    - info
    - --component-log-level
    - wasm:debug,http:debug,router:debug
    - --service-cluster
    - proxy
    expose:
    - "80"
    - "8001"
    ports:
    - "18000:80"
    - "18001:8001"
    volumes:
    - ${PWD}/e2e/envoy.yaml:/etc/envoy.yaml
  upstream:
    image: quay.io/kuadrant/authorino-examples:talker-api
    environment:
      PORT: 3000
    expose:
    - "3000"
  tester:
    build:
      context: ${PWD}
      dockerfile: e2e/Dockerfile.tester
    depends_on:
      - envoy
      - rlsbin
    command: /test/run-all.sh
    volumes:
      - ${PWD}/e2e/:/test/
